language: node_js

node_js: 0.10

env:
  global:
    - secure: "a1+XryJ+Mhsmmv6N3CegrSTYqCyeTfwY9a1w8HEpLW796IbTlzYN9TsddHDnfOmuKLQyf4nAgM5tRkrf+pFnBBmw2us65GBGltldzSqp5KElIAHghhsveoVS6njx6D+EUzzCNdePMXDKkIPBIqeZEq+2Cu0mzpZy751tuh2h6cg="
    - secure: "R0KYNHt8IpYYbf6HdkYYIvcmDaRoj7izd5NPFqGYU0Zvjnfg3MykBH6CKycTyDwEHmbLEyW0kPTAweBMeRZGTSUpucKtVtGNBZgyda6xas3CSe8n4KvE+YVoq1dCq+zmTPAZw4rKLczVDvSHzTh2pgAIxDB/r9o4na22diV4X34="
    - secure: "COxwi1GuBQOYVnZtIQqCFos2v99+L7dIvN1ba+ve0QjFVtwDVG+yDfV9BbT+SWWbR4CCZGMx7LB7Pt9oK6fBbvkdI8BGn59P4hf4L2GEyiddA6V6N+09h3emEJsHc4IIqVkwfRm82yw5w3YWhTkcUfi0mBn/1sMASYwUIgMwwL8="
    - secure: "bdgJUEbPQ4xgLI2PM3jbC2RzIs+XRBfxzoq38b7w8T6RiCzRp2hae51SG4tcWqUNwshtY3HoAKTXwGmM8MWx6kwb8BJ+hsY8NzcBcft9gct/gJ89zA9upRnmnfzBmdbwXk1iDaFAmG4aKaUQsd6qwTqYip6UFZKPE/cHKCpY4hQ="
    - secure: "ipvXACA3RpS8EL2kleCshZ8Ys3t8ehaUmKk8qcLNhDltnLTLKJqhR9r4aZc9wiTafkUlp3lYUQpn54yqwxJoul+H+vcWUqvwzLXJLyoTlopyI9AV+DHhuC+CWzrd68UUHlvbiETMsN3ersciaV907s/415CcE3Bx8rdO6xRs3v0="
    - secure: "FBCyQQpcsOreZ0khYc0YNZWFTo6JJVyp8HwL8/FNRP6ecRAI2jKEgfWPiIUuPBtRO+MIfmWm9fRKJtmi8XMHtQc6aDt+gd/uqLICVd00K6cN3ui89uc3QpJiLjMONQ6WJmYjDNCNKQgYq3pP4WRk+MZyE/G++Wp1kBkF9HyBpdE="
    - secure: "PrybvamC97PyuwgE3QJQkUAKDdYqjhDfJSqcpgIH+38TIEoRUEyZFe4Dho79MAc/7t8YynQKhv6yJBWTI8b/aHztzBpV/gHNkp9BA39+Joh8/JHPXCnTTdhH1BxQdmcAX3rnZIzichA5m4W0OL7beIQgfSrezNntOYv9CS+U3Ao="
    - secure: "Wc+aV50jtAPDqf0/eQKyzbdG38/oqzKfOUgduVxw0IGfpnokYr0o40OnJ9jxnLID6Z/y9uTAEOXiuCDJQQyOaFdaX+fB/UvPXr0YHh1FBG/wujfOswesplQ5HzJulfh5dB6r7nE1bhinHJLAcklYfKjzaTJ3hTZzLXrsYGGKrGc="

before_install:
  - npm config set loglevel error

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nginx
  - nginx -c .travis/nginx.conf -p .
  - gem install jsduck
  - npm -g install grunt-cli
  - npm -g install bower
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  -  grunt travis &&
    .travis/ghpages-deploy.sh