// Do not edit this manually it was automatically generated by the keyboard_layout_generator
'use strict';

(function() {
    var isGecko = Stimuli.core.Support.isGecko;
    var isIE = Stimuli.core.Support.isIE;

    Stimuli.keyboard.layout.__platform__.__layout__ = {
        unicode: __unicode__,
        patterns: __patterns__,
        table: __table__
    };

    Stimuli.core.Object.merge(Stimuli.keyboard.layout.__platform__.__layout__, Stimuli.keyboard.layout.Generic);

})();